### ISSUE TITLE
Sm4sh doesn't work at all

### ISSUE THREAD

**Issue by SubstituteR** [meladroit/svdt#13]
Emergency mode dumps nothing.  (And sm4sh is known to glitch the menu out.)

**Comment by suloku** [comment]
Are you using latest version?
Does it happen with 10.42b?

**Comment by SubstituteR** [comment]
Happens with both 10.42B and 10.42C
On latest firmware, O3DS, newest Sm4sh update.
I ended up using SDM to dump and inject the save for Sm4sh since the emergency mode just made an empty folder.

**Comment by suloku** [comment]
Does it happen only with SSB or does it work fine for other games (even if they don't glitch the screen it should be the same for emergency mode)?

**Comment by SubstituteR** [comment]
Oras and XY dump fine (both modes)

**Comment by meladroit** [comment]
Does it work with SSB on an even older svdt? Say, [svdt 0.2a](https://github.com/meladroit/svdt/releases/tag/v0.2a)?

**Comment by SubstituteR** [comment]
Will test when I get home

**Comment by meladroit** [comment]
FYI, @suloku, if this works with the ancient version of svdt, we should move things around so that emergency backup/inject takes place _before_ amInit() (then move the backup into the title directory afterwards if titleTitle_set > 0), and see if that makes things work. Unfortunately, by 'we' I'm afraid I mean mostly you, as I'm drowning in other work at the moment.

**Comment by meladroit** [comment]
Also worth noting that emergency backups are automatic in v0.10.42c (no keypresses required), but require holding down the left shoulder button in v0.2a.

**Comment by suloku** [comment]
I may be able to get my hands on a o3ds and SSB cartridge tomorrow if SubstituteCS can't get it working, but I wouldn't be able to test until friday.

SubstituteCS, aside the fact that backups are automatic in newest versions without a "disable_autobackups" file, notice that latest  10.42C will output the save to /svdt/Smash Bros.../timestamp; maybe you are expecting /svdt/timestamp and that's why you don't find the save?

**Comment by SubstituteR** [comment]
This is what I get with the latest version (successful auto dump of ORAS, while nothing is dumped for Sm4sh), http://i.imgur.com/Dt54TIf.png
Additionally, after running an older version (v1.10) the folders for the dump (e.g. "20110418_203750") are created, but the save file is still not present.

EDIT:
0.2A doesn't dump anything either.
0.2A emergency dump mode is with the shoulder button right?

**Comment by suloku** [comment]
OK, I have an O3DS with smash bros cartridge, but what's interesting is that emergency mode does not work for this game even on New 3DS, so the problem must be some kind of bug, which is in fact better than amInit() being the culprit.

I'll try to work it out this afternoon.

EDIT: I doesn't work either with normal directory copying to /svdt/ dir trough root dir selection, but copying to current directory works fine, so it's probably some silly bug

EDIT2: kind of fixed it, need to check emergency mode on O3DS

EDIT3: working in o3DS. I fixed some more things in the process as well.

**Comment by suloku** [comment]
https://github.com/meladroit/svdt/pull/14

**Comment by meladroit** [comment]
@SubstituteCS, does v0.10.42d fix this for you? If #14 is supposed to be the fix, theoretically it should have worked with 0.2a, though. (And yes, for 0.2a, you hold down the left shoulder button as you launch it from the homebrew launcher, starting at or before the target app selection screen.)

**Comment by SubstituteR** [comment]
The issue is fixed (I have not tested injecting yet, I might later, but theoretically it should work.)
Good show!
