### ISSUE TITLE
"svdt"

### ISSUE THREAD

**Issue by RuinTD** [meladroit/svdt#15]
Smealum's "tdvs" is saveedit in reverse without the vowels. So, the SMDH description should say "it's saveedit without the vowels" instead of "it's tdvs in reverse without the vowels"

**Comment by suloku** [comment]
Well, smea did in fact say so in twitter... I guess it's worth changing for next version

**Comment by meladroit** [comment]
I've been aware of this since the start. The whole joke with the name is that it's tdvs in reverse insofar as the fact that it's reverse-engineered, but tdvs was 'savedata' disemvowelised and _in reverse_ to begin with, and 'without the vowels' was my way of trying to make sure everyone knew that I was aware of this (because of course tdvs doesn't even have any vowels, and so it's an obvious reference to smea's tweet). It still ended up being a terrible joke, but one I'm not going to fix.

**Comment by suloku** [comment]
Oh I see, nice one, I feel slow now
